---
- name: 'Include OS specific vars'
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
  no_log: true

- name: 'RHEL-like specific tasks'
  block:
    - name: 'Enable RedHat CodeReady Builder repo'
      community.general.rhsm_repository:
        name: "codeready-builder-for-rhel-{{ ansible_facts['distribution_major_version'] }}-x86_64-rpms"
        state: 'enabled'
      when: ansible_facts['distribution'] == 'RedHat'

    - name: 'Ensure EPEL'
      ansible.builtin.dnf:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
        state: 'present'
        disable_gpg_check: true
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - rt_setup_repos

- name: 'Ensure dependencies'
  ansible.builtin.package:
    name: "{{ rt_package_dependencies }}"
    state: 'present'
    update_cache: true

- name: 'Ensure RT5 sources'
  ansible.builtin.git:
    repo: 'https://github.com/bestpractical/rt'
    version: "rt-{{ rt_version }}"
    dest: '/root/request_tracker'

- name: 'Ensure SELinux context for writable dirs'
  community.general.sefcontext:
    target: "/opt/rt5/{{ selinux_context['dir'] }}(/.*)?"
    setype: "{{ selinux_context['type'] }}"
    state: 'present'
  loop:
    - dir: 'var'
      type: 'httpd_sys_content_rw_t'
  loop_control:
    loop_var: 'selinux_context'
  when: ansible_facts['os_family'] == 'RedHat'

- name: 'Prepare installation (1/2)'
  ansible.builtin.shell: |
    export PERL_MM_USE_DEFAULT=1
    /usr/bin/cpan quit
    cd /root/request_tracker
    autoconf
  changed_when: true

- name: 'Prepare installation (2/2)'
  ansible.builtin.shell: |
    cd /root/request_tracker
    ./configure \
      --enable-graphviz  --enable-externalauth --enable-smime \
      --with-attachment-store=database > /root/request_tracker_configure.log 2>&1
  changed_when: true

- name: 'Ensure CPAN dependencies (this may take a while)'
  ansible.builtin.shell: |
    cd /root/request_tracker
    make fixdeps > /root/request_tracker_fixdeps.log 2>&1
  changed_when: true

- name: 'Install RT'
  ansible.builtin.shell: |
    cd /root/request_tracker
    make install > /root/request_tracker_install.log 2>&1
  changed_when: true

- name: 'Ensure RT Site config'
  ansible.builtin.template:
    src: 'RT_SiteConfig.pm.j2'
    dest: '/opt/rt5/etc/RT_SiteConfig.pm'
    owner: 'root'
    group: "{{ rt_apache_group }}"
    mode: '0660'
    validate: 'perl -c %s'
  no_log: false

- name: 'Ensure database semaphore file for manual DB setup'
  ansible.builtin.file:
    path: '/opt/rt5/ansible_db_init_done'
    state: 'touch'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: rt_manual_database_setup

- name: 'Initialize database'
  ansible.builtin.shell: |
    /opt/rt5/sbin/rt-setup-database --action init --skip-create
    /opt/rt5/sbin/rt-setup-fulltext-index --noask --dba {{ rt_database_admin }} --dba-password {{ rt_database_admin_password }}
    touch /opt/rt5/ansible_db_init_done
  args:
    creates: '/opt/rt5/ansible_db_init_done'
  no_log: true

- name: 'Restore SELinux contexts'
  ansible.builtin.command: restorcon -ir /opt/rt5
  changed_when: true
  when: ansible_facts['os_family'] == 'RedHat'

- name: 'Do manual database setup'
  ansible.builtin.debug:
    msg: |
      Installation of Request Tracker is now complete and you selected manual database setup

      Please import the database to the configured MySQL server now and run all
      required steps for manual DB upgrade. This can be something like below:

      == 8< ==
      rt-setup-database --action upgrade --force --skip-create --upgrade-from x.x.x --upgrade-to {{ rt_version }}
      == 8< ==
  when: rt_manual_database_setup
